# Generated by Django 3.0.2 on 2020-02-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SrpUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FI_File_Upload', models.FileField(upload_to='fitting_instructions/')),
                ('BOM_File_Upload', models.FileField(upload_to='bom_files/')),
            ],
        ),
    ]
