# Generated by Django 3.0.2 on 2020-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_coordinates_upload', models.FileField(upload_to='SRP_Database/')),
                ('pick_skills_upload', models.FileField(upload_to='SRP_Database/')),
                ('operation_skills_upload', models.FileField(upload_to='SRP_Database/')),
            ],
        ),
        migrations.CreateModel(
            name='SrpClusterDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_time', models.TimeField(auto_now=True)),
                ('original', models.TextField()),
                ('operation', models.TextField()),
                ('target', models.TextField()),
                ('relation', models.TextField()),
                ('absolute_coordinates_root_relation', models.TextField()),
                ('absolute_coordinates_root_target', models.TextField()),
                ('custom_pick_skill', models.TextField()),
                ('safety_highway_points', models.TextField()),
                ('target_coordinates_abs', models.TextField()),
                ('safe_move_to_target', models.TextField()),
                ('operation_skill', models.TextField()),
            ],
        ),
    ]
