# Generated by Django 3.0.2 on 2020-02-12 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SRP_APP', '0002_db_uploads_srp_cluster_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpclusterdb',
            name='pathplanning_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='srpclusterdb',
            name='operation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='srpclusterdb',
            name='original',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='srpclusterdb',
            name='relation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='srpclusterdb',
            name='target',
            field=models.CharField(max_length=500),
        ),
    ]
